<a href="https://colab.research.google.com/github/HauThierry/HauThierry/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
np.array([1,2,3])
np.arange(10)
np.arange(8).reshape(4,2)
np.zeros((3,2))
np.random.rand(10)
np.random.random(size=(3,2))


array([[0.68104039, 0.53380736],
       [0.32563515, 0.4865949 ],
       [0.14368765, 0.46536665]])

In [ ]:
myArray = np.random.rand(5)
print(myArray)
print(type(myArray))
print(myArray[3])

myArray_multidimension = np.random.rand(6).reshape(3,2)
print(myArray_multidimension)
print(myArray_multidimension[1:,1])


[0.02919617 0.3836871  0.14274377 0.45832157 0.66250085]
<class 'numpy.ndarray'>
0.4583215652399376
[[0.19649256 0.53617239]
 [0.0016855  0.46799743]
 [0.0337733  0.59132801]]
[0.46799743 0.59132801]


In [ ]:
print(myArray_multidimension.shape) #forme d'aray (nombre d'elements, nombre d'axes)
print(myArray_multidimension.ndim) #le nombre de dimension
print(myArray_multidimension.size) #le nombre total déelement dans mon array

(3, 2)
2
6


In [ ]:
#fonctions mathématique np.cos, np.log, np.exp, np.sqrt etc...
myArray = np.arange(10).reshape(5,2)
print(myArray)
print(np.cos(myArray))
print(np.exp(myArray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]
[[1.00000000e+00 2.71828183e+00]
 [7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03]]


In [ ]:
np.var(myArray) #variance


np.float64(8.25)

In [ ]:
#fonctions utiles np.sum , np.min, np.max, np.mean
print(myArray)
print(myArray.min())
print(myArray.max())
print(np.max(myArray))
print(np.mean(myArray))


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
0
9
9
4.5


In [ ]:
# produit elements par element *
A = np.arange(16).reshape(4,4)
print(A)
B = np.random.rand(16).reshape(4,4)
print(B)

print(A*B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.37840275 0.15953704 0.301167   0.17688189]
 [0.53905793 0.49426061 0.093307   0.75924965]
 [0.99716816 0.97627244 0.27018855 0.97361468]
 [0.69359891 0.01033414 0.71150157 0.11847514]]
[[ 0.          0.15953704  0.602334    0.53064567]
 [ 2.15623173  2.47130307  0.55984199  5.31474755]
 [ 7.97734529  8.78645193  2.70188554 10.70976148]
 [ 8.32318687  0.13434388  9.96102197  1.77712707]]


In [ ]:
# produit matriciel @ ou array1.dot(array2)
print(A @ B)
print(A.dot(B))

[[ 4.61419097  2.47780792  2.76818882  3.06190442]
 [15.04710196  9.03942488  8.27284531 11.17478986]
 [25.48001295 15.60104184 13.7775018  19.28767529]
 [35.91292394 22.1626588  19.28215829 27.40056073]]
[[ 4.61419097  2.47780792  2.76818882  3.06190442]
 [15.04710196  9.03942488  8.27284531 11.17478986]
 [25.48001295 15.60104184 13.7775018  19.28767529]
 [35.91292394 22.1626588  19.28215829 27.40056073]]


In [ ]:
#Transposé .T ou np.transpose()
print(A)
print(A.T)
print(np.transpose(A))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [ ]:
#Matrice inversible https://fr.wikipedia.org/wiki/Matrice_inversible
#np.linalg.inv(matrix) matrix carré a non singulière
np.linalg.inv(np.random.rand(16).reshape(4,4))

array([[ 2.32061149, -2.78041324, -0.16685697, -0.74482012],
       [-1.32428832,  2.74879021, -1.50952389,  1.19424982],
       [-0.65583054, -0.07492286,  0.41203354,  1.20690626],
       [ 1.02622231,  0.23276062,  2.75602407, -2.56691514]])