<a href="https://colab.research.google.com/github/HauThierry/HauThierry/blob/main/tableaux_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Les tableaux NumPy
1. Création de tableaux NumPy
a. Créer un tableau à une dimension

In [1]:
import numpy as np

vecteur = np.array([1,2,3,4])
print("vecteur = ", vecteur)


vecteur =  [1 2 3 4]


b. Créer un tableau à plusieurs dimensions

In [2]:
import numpy as np

vecteur_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("vecteur_2d = \n", vecteur_2d)


vecteur_2d = 
 [[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np

vecteur_3d = np.array([[[1,1,1],[1,1,1]],[[2,2,2],[2,2,2]]])
print("vecteur_3d = \n", vecteur_3d)


vecteur_3d = 
 [[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]


2. Les dimensions d’un tableau NumPy


In [6]:
import numpy as np

vecteur = np.array([1,2,3,4])
print("vecteur : ", vecteur)
print(f"le nombre de dimensions de vecteur = {vecteur.ndim}")
print(f"les dimensions du vecteur vecteur = {vecteur.shape}")


vecteur :  [1 2 3 4]
le nombre de dimensions de vecteur = 1
les dimensions du vecteur vecteur = (4,)


In [11]:
import numpy as np

vecteur_3d = np.array([[[1,1,1,1],[1,1,1,1],[1,1,1,1]],
                       [[2,2,2,2],[2,2,2,2],[2,2,2,2]]])
print("vecteur_3d : \n", vecteur_3d)
print(f"le nombre de dimensions de vecteur_3d = {vecteur_3d.ndim}")
print(f"les dimensions du vecteur vecteur_3d = {vecteur_3d.shape}")

# L’attribut shape a retourné la valeur (2,3,4). Ce 3-uplet peut être lu comme suit : le tableau vecteur_3d contient deux matrices, et chacune de ces deux matrices est définie par trois lignes, et enfin chacune des lignes des deux matrices est définie par quatre colonnes.

vecteur_3d : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
le nombre de dimensions de vecteur_3d = 3
les dimensions du vecteur vecteur_3d = (2, 3, 4)


3. Le type et la taille d’un tableau NumPy


In [17]:
import numpy as np

vecteur_1 = np.array([[1,2,3,4],[5,6,7,8]], dtype='int16')
vecteur_2 = np.array([[1,2,3,4],[5,6,7,8]], dtype='int32')
vecteur_3 = np.array([[1,2,3,4],[5,6,7,8]], dtype='float')

print(f"- Le type de vecteur_1 = {type(vecteur_1)}\n"
     +f"- Le type de vecteur_2 = {type(vecteur_2)}\n"
     +f"- Le type de vecteur_3 = {type(vecteur_3)}\n")

print(f"- Le type des éléments de vecteur_1 = {vecteur_1.dtype}\n"
     +f"- Le type des éléments de vecteur_2 = {vecteur_2.dtype}\n"
     +f"- Le type des éléments de vecteur_3 = {vecteur_3.dtype}\n")

print(f"- Taille de chaque élément de vecteur_1 = {vecteur_1.itemsize} octets\n"
     +f"- Taille de chaque élément de vecteur_2 = {vecteur_2.itemsize} octets\n"
     +f"- Taille de chaque élément de vecteur_3 = {vecteur_3.itemsize} octets\n")

print(f"- Nombre d'éléments dans vecteur_1 = {vecteur_1.size}\n"
     +f"- Nombre d'éléments dans vecteur_2 = {vecteur_2.size}\n"
     +f"- Nombre d'éléments dans vecteur_3 = {vecteur_3.size}\n")

print(f"- Taille totale de vecteur_1 = {vecteur_1.nbytes} octets\n"
    +f"- Taille totale de vecteur_2 = {vecteur_2.nbytes}  octets\n"
    +f"- Taille totale de vecteur_3 = {vecteur_3.nbytes}  octets")

- Le type de vecteur_1 = <class 'numpy.ndarray'>
- Le type de vecteur_2 = <class 'numpy.ndarray'>
- Le type de vecteur_3 = <class 'numpy.ndarray'>

- Le type des éléments de vecteur_1 = int16
- Le type des éléments de vecteur_2 = int32
- Le type des éléments de vecteur_3 = float64

- Taille de chaque élément de vecteur_1 = 2 octets
- Taille de chaque élément de vecteur_2 = 4 octets
- Taille de chaque élément de vecteur_3 = 8 octets

- Nombre d'éléments dans vecteur_1 = 8
- Nombre d'éléments dans vecteur_2 = 8
- Nombre d'éléments dans vecteur_3 = 8

- Taille totale de vecteur_1 = 16 octets
- Taille totale de vecteur_2 = 32  octets
- Taille totale de vecteur_3 = 64  octets


4. Fonction d’initialisation de tableaux NumPy

In [18]:
import numpy as np
vecteur_1 = np.zeros(10)
vecteur_2 = np.zeros(10, dtype='int32')
vecteur_3 = np.ones((3,4), dtype='int16')
print("vecteur_1 = ", vecteur_1)
print("vecteur_2 = ", vecteur_2)
print("vecteur_3 =\n ", vecteur_3)


vecteur_1 =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vecteur_2 =  [0 0 0 0 0 0 0 0 0 0]
vecteur_3 =
  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
import numpy as np
vecteur_1 = np.full((3,4), 5)
vecteur_2 = np.full_like(vecteur_1, 10)
vecteur_3 = np.identity(3)
print("vecteur_1 =\n ", vecteur_1)
print("vecteur_2 =\n", vecteur_2)
print("vecteur_3 = \n", vecteur_3)


vecteur_1 =
  [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
vecteur_2 =
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
vecteur_3 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Accéder aux données d’un tableau NumPy
1. Accès aux données d’un tableau à une dimension