<a href="https://colab.research.google.com/github/HauThierry/HauThierry/blob/main/tableaux_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Les tableaux NumPy
1. Création de tableaux NumPy
a. Créer un tableau à une dimension

In [ ]:
import numpy as np

vecteur = np.array([1,2,3,4])
print("vecteur = ", vecteur)


vecteur =  [1 2 3 4]


b. Créer un tableau à plusieurs dimensions

In [ ]:
import numpy as np

vecteur_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("vecteur_2d = \n", vecteur_2d)


vecteur_2d = 
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np

vecteur_3d = np.array([[[1,1,1],[1,1,1]],[[2,2,2],[2,2,2]]])
print("vecteur_3d = \n", vecteur_3d)


vecteur_3d = 
 [[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]


2. Les dimensions d’un tableau NumPy


In [ ]:
import numpy as np

vecteur = np.array([1,2,3,4])
print("vecteur : ", vecteur)
print(f"le nombre de dimensions de vecteur = {vecteur.ndim}")
print(f"les dimensions du vecteur vecteur = {vecteur.shape}")


vecteur :  [1 2 3 4]
le nombre de dimensions de vecteur = 1
les dimensions du vecteur vecteur = (4,)


In [ ]:
import numpy as np

vecteur_3d = np.array([[[1,1,1,1],[1,1,1,1],[1,1,1,1]],
                       [[2,2,2,2],[2,2,2,2],[2,2,2,2]]])
print("vecteur_3d : \n", vecteur_3d)
print(f"le nombre de dimensions de vecteur_3d = {vecteur_3d.ndim}")
print(f"les dimensions du vecteur vecteur_3d = {vecteur_3d.shape}")

# L’attribut shape a retourné la valeur (2,3,4). Ce 3-uplet peut être lu comme suit : le tableau vecteur_3d contient deux matrices, et chacune de ces deux matrices est définie par trois lignes, et enfin chacune des lignes des deux matrices est définie par quatre colonnes.

vecteur_3d : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
le nombre de dimensions de vecteur_3d = 3
les dimensions du vecteur vecteur_3d = (2, 3, 4)


3. Le type et la taille d’un tableau NumPy


In [ ]:
import numpy as np

vecteur_1 = np.array([[1,2,3,4],[5,6,7,8]], dtype='int16')
vecteur_2 = np.array([[1,2,3,4],[5,6,7,8]], dtype='int32')
vecteur_3 = np.array([[1,2,3,4],[5,6,7,8]], dtype='float')

print(f"- Le type de vecteur_1 = {type(vecteur_1)}\n"
     +f"- Le type de vecteur_2 = {type(vecteur_2)}\n"
     +f"- Le type de vecteur_3 = {type(vecteur_3)}\n")

print(f"- Le type des éléments de vecteur_1 = {vecteur_1.dtype}\n"
     +f"- Le type des éléments de vecteur_2 = {vecteur_2.dtype}\n"
     +f"- Le type des éléments de vecteur_3 = {vecteur_3.dtype}\n")

print(f"- Taille de chaque élément de vecteur_1 = {vecteur_1.itemsize} octets\n"
     +f"- Taille de chaque élément de vecteur_2 = {vecteur_2.itemsize} octets\n"
     +f"- Taille de chaque élément de vecteur_3 = {vecteur_3.itemsize} octets\n")

print(f"- Nombre d'éléments dans vecteur_1 = {vecteur_1.size}\n"
     +f"- Nombre d'éléments dans vecteur_2 = {vecteur_2.size}\n"
     +f"- Nombre d'éléments dans vecteur_3 = {vecteur_3.size}\n")

print(f"- Taille totale de vecteur_1 = {vecteur_1.nbytes} octets\n"
    +f"- Taille totale de vecteur_2 = {vecteur_2.nbytes}  octets\n"
    +f"- Taille totale de vecteur_3 = {vecteur_3.nbytes}  octets")

- Le type de vecteur_1 = <class 'numpy.ndarray'>
- Le type de vecteur_2 = <class 'numpy.ndarray'>
- Le type de vecteur_3 = <class 'numpy.ndarray'>

- Le type des éléments de vecteur_1 = int16
- Le type des éléments de vecteur_2 = int32
- Le type des éléments de vecteur_3 = float64

- Taille de chaque élément de vecteur_1 = 2 octets
- Taille de chaque élément de vecteur_2 = 4 octets
- Taille de chaque élément de vecteur_3 = 8 octets

- Nombre d'éléments dans vecteur_1 = 8
- Nombre d'éléments dans vecteur_2 = 8
- Nombre d'éléments dans vecteur_3 = 8

- Taille totale de vecteur_1 = 16 octets
- Taille totale de vecteur_2 = 32  octets
- Taille totale de vecteur_3 = 64  octets


4. Fonction d’initialisation de tableaux NumPy

In [ ]:
import numpy as np
vecteur_1 = np.zeros(10)
vecteur_2 = np.zeros(10, dtype='int32')
vecteur_3 = np.ones((3,4), dtype='int16')
print("vecteur_1 = ", vecteur_1)
print("vecteur_2 = ", vecteur_2)
print("vecteur_3 =\n ", vecteur_3)


vecteur_1 =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vecteur_2 =  [0 0 0 0 0 0 0 0 0 0]
vecteur_3 =
  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
import numpy as np
vecteur_1 = np.full((3,4), 5)
vecteur_2 = np.full_like(vecteur_1, 10)
vecteur_3 = np.identity(3)
print("vecteur_1 =\n ", vecteur_1)
print("vecteur_2 =\n", vecteur_2)
print("vecteur_3 = \n", vecteur_3)


vecteur_1 =
  [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
vecteur_2 =
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
vecteur_3 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Accéder aux données d’un tableau NumPy
1. Accès aux données d’un tableau à une dimension

In [ ]:
import numpy as np

vecteur_1d = np.array([1,2,3,4,5,6,7,8,9,10])
print("vecteur_1d = ",vecteur_1d)
print("vecteur_1d[1] = ", vecteur_1d[1])
print("vecteur_1d[[1,3]] = ", vecteur_1d[[1,3]])
print("vecteur_1d[[0,-1]] = ", vecteur_1d[[0,-1]])
print("vecteur_1d[2:6] = ", vecteur_1d[2:6])
print("vecteur_1d[2:] = ", vecteur_1d[2:])
print("vecteur_1d[0:10:2] = ", vecteur_1d[0:10:2])


vecteur_1d =  [ 1  2  3  4  5  6  7  8  9 10]
vecteur_1d[1] =  2
vecteur_1d[[1,3]] =  [2 4]
vecteur_1d[[0,-1]] =  [ 1 10]
vecteur_1d[2:6] =  [3 4 5 6]
vecteur_1d[2:] =  [ 3  4  5  6  7  8  9 10]
vecteur_1d[0:10:2] =  [1 3 5 7 9]


2. Accès aux données d’un tableau à deux dimensions

In [ ]:
import numpy as np

vecteur_2d = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12],
                       [13,14,15]])

print("vecteur_2d[0,0] = ",vecteur_2d[0,0])
print("vecteur_2d[1,1] = ",vecteur_2d[2,1])
print("vecteur_2d[2,2] = ",vecteur_2d[4,2],"\n")
print("vecteur_2d[:,:] =\n ",vecteur_2d[:,:],"\n")
print("vecteur_2d[1,:] = ",vecteur_2d[1,:],"\n")
print("vecteur_2d[:,1] = ",vecteur_2d[:,1],"\n")
print("vecteur_2d[0:5:2,1] = ",vecteur_2d[0:5:2,1],"\n")


vecteur_2d[0,0] =  1
vecteur_2d[1,1] =  8
vecteur_2d[2,2] =  15 

vecteur_2d[:,:] =
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] 

vecteur_2d[1,:] =  [4 5 6] 

vecteur_2d[:,1] =  [ 2  5  8 11 14] 

vecteur_2d[0:5:2,1] =  [ 2  8 14] 



3. Accès aux données d’un tableau à trois dimensions

In [ ]:
import numpy as np

vecteur_3d = np.array([[[1,0,0],[0,0,0]],
                      [[0,2,0],[0,0,3]]])

print("vecteur_3d[0,0,0] = ", vecteur_3d[0,0,0])
print("vecteur_3d[1,0,1] = ", vecteur_3d[1,0,1])
print("vecteur_3d[1,1,2] = ", vecteur_3d[1,1,2])

vecteur_3d[0,0,0] =  1
vecteur_3d[1,0,1] =  2
vecteur_3d[1,1,2] =  3


Modifier les données d’un tableau NumPy

In [ ]:
import numpy as np

vecteur = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

vecteur[1,1] = 99
print("Après vecteur[1,1] = 99 le tableau devient:\n",vecteur,
      end="\n\n")

vecteur[0,:] = 99
print("Après vecteur[0,:] = 99 le tableau devient:\n",vecteur,
      end="\n\n")

vecteur[:,2] = -99
print("Après vecteur[:,2] = -99 le tableau devient:\n",vecteur,
      end="\n\n")


Après vecteur[1,1] = 99 le tableau devient:
 [[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]

Après vecteur[0,:] = 99 le tableau devient:
 [[99 99 99]
 [ 4 99  6]
 [ 7  8  9]]

Après vecteur[:,2] = -99 le tableau devient:
 [[ 99  99 -99]
 [  4  99 -99]
 [  7   8 -99]]



Copier un tableau NumPy dans un autre tableau NumPy

In [ ]:
import numpy as np

vecteur_1 = np.array([1,2,3])
vecteur_2 = vecteur_1
vecteur_2[2] = 99
print("vecteur_1 =", vecteur_1)
print("vecteur_2 =", vecteur_2)


vecteur_1 = [ 1  2 99]
vecteur_2 = [ 1  2 99]


In [ ]:
import numpy as np

vecteur_1 = np.array([1,2,3])
vecteur_2 = vecteur_1.copy()
vecteur_2[2] = 99
print("vecteur_1 =", vecteur_1)
print("vecteur_2 =", vecteur_2)


vecteur_1 = [1 2 3]
vecteur_2 = [ 1  2 99]


Algèbre linéaire avec NumPy
1. Opérations mathématiques de base avec NumPy

In [ ]:
import numpy as np

vecteur_1 = np.array([1,2,3,4,5])
print("vecteur_1 = ",vecteur_1)
print("vecteur_1 + 2 = ",vecteur_1+2)
print("vecteur_1 - 2 = ",vecteur_1-2)
print("vecteur_1 * 2 = ",vecteur_1*2)
print("vecteur_1 / 2 = ",vecteur_1/2)
print("vecteur_1 ** 2 = ",vecteur_1**2)
print("Cosinus(vecteur_1) = ",np.cos(vecteur_1))

vecteur_2 = np.array([5,4,3,2,1])
print("vecteur_2 = ",vecteur_2)
print("vecteur_1 * vecteur_2 = ",vecteur_1*vecteur_2)


vecteur_1 =  [1 2 3 4 5]
vecteur_1 + 2 =  [3 4 5 6 7]
vecteur_1 - 2 =  [-1  0  1  2  3]
vecteur_1 * 2 =  [ 2  4  6  8 10]
vecteur_1 / 2 =  [0.5 1.  1.5 2.  2.5]
vecteur_1 ** 2 =  [ 1  4  9 16 25]
Cosinus(vecteur_1) =  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
vecteur_2 =  [5 4 3 2 1]
vecteur_1 * vecteur_2 =  [5 8 9 8 5]


2. Opérations sur les matrices avec NumPy

In [ ]:
import numpy as np

mat_1 = np.random.randint(-10,10, size=(3,4))
mat_2 = np.random.randint(-10,10, size=(4,2))

print("mat_1 :\n", mat_1,"\n")
print("mat_2 :\n", mat_2)
result = np.matmul(mat_1, mat_2)
print("mat_1 * mat_2 :\n", result)


mat_1 :
 [[ 3  6  4 -3]
 [-7  7 -9  5]
 [ 5 -3 -7 -6]] 

mat_2 :
 [[-3  3]
 [-3  6]
 [-9  8]
 [ 5 -4]]
mat_1 * mat_2 :
 [[-78  89]
 [106 -71]
 [ 27 -35]]


Réorganiser des tableaux NumPy

1. Restructurer un tableau NumPy

In [ ]:
import numpy as np

mat_1 = np.array([[1,2,3,4],[5,6,7,8]])
mat_2 = mat_1.reshape(4,2)
mat_3 = mat_1.reshape(2,2,2)
print("mat_1:\n", mat_1)
print("mat_2:\n", mat_2)
print("mat_3:\n", mat_3)


mat_1:
 [[1 2 3 4]
 [5 6 7 8]]
mat_2:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
mat_3:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2. Superposer des tableaux NumPy

In [ ]:
import numpy as np

vec_1 = np.array([1,2,3,4,5])
vec_2 = np.array([6,7,8,9,10])

v_stack_vec = np.vstack([vec_1, vec_2])
print("Avec vstack:\n",v_stack_vec)

v_stack_big_vec = np.vstack([vec_1, vec_2,vec_1, vec_2])
print("\nEncore avec vstack:\n",v_stack_big_vec)

h_stack_vec = np.hstack([vec_1, vec_2])
print("\nAvec hstack:\n",h_stack_vec)


Avec vstack:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Encore avec vstack:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Avec hstack:
 [ 1  2  3  4  5  6  7  8  9 10]


Statistiques descriptives avec NumPy

In [ ]:
import numpy as np

mat_1 = np.random.randint(-10,10, size=(5,5))
print("mat_1 :\n", mat_1)

min_value = np.min(mat_1)
print(f"\nLa valeur minimale de toute la matrice est: {min_value}\n")
max_value = np.max(mat_1)
print(f"La valeur maximale de toute la matrice est: {max_value}\n")

min_value_by_col = np.min(mat_1, axis=0)
print(f"Les valeurs minimales par colonne sont: {min_value_by_col}\n")
min_value_by_row = np.min(mat_1, axis=1)
print(f"Les valeurs minimales par ligne sont: {min_value_by_row}\n")

mean_value_by_col = np.mean(mat_1, axis=0)
print(f"Les moyennes par colonne sont: {mean_value_by_col}\n")
std_by_col = np.std(mat_1, axis=0)
print(f"Les écarts-types par colonne sont: {std_by_col}\n")
sum_by_row = np.sum(mat_1, axis=1)
print(f"Les sommes par ligne sont: {sum_by_row}\n")


mat_1 :
 [[-7 -8  7 -4 -9]
 [ 6  7  0 -3  9]
 [ 5  0 -7  9  3]
 [ 4 -7  3 -1  6]
 [-7 -5  4  8 -7]]

La valeur minimale de toute la matrice est: -9

La valeur maximale de toute la matrice est: 9

Les valeurs minimales par colonne sont: [-7 -8 -7 -4 -9]

Les valeurs minimales par ligne sont: [-9 -3 -7 -7 -7]

Les moyennes par colonne sont: [ 0.2 -2.6  1.4  1.8  0.4]

Les écarts-types par colonne sont: [5.9126982  5.535341   4.7581509  5.5641711  7.14422844]

Les sommes par ligne sont: [-21  19  10   5  -7]



Lire des données NumPy à partir d’un fichier

In [ ]:
import numpy as np

my_data = np.genfromtxt("ozone.csv", delimiter =',')
# my_data =  my_data.astype('int32') # Commenté car le fichier contient probablement des en-têtes ou des chaînes de caractères qui empêcheront la conversion directe en int32.
print(my_data)

[[        nan         nan         nan ...         nan         nan
          nan]
 [ 1.0000e+00  9.1000e+01  9.3200e+01 ...         nan  9.5000e+00
  -6.4350e-01]
 [ 1.0000e+00  1.0000e+02  1.0460e+02 ...         nan  8.0100e+00
  -4.9960e-02]
 ...
 [ 0.0000e+00  7.4000e+01  1.9840e+02 ...         nan  4.0311e+00
   1.2435e-01]
 [ 0.0000e+00  1.2100e+02  1.9170e+02 ...         nan  3.8000e+00
   0.0000e+00]
 [ 1.0000e+00  9.3000e+01  2.2120e+02 ...         nan  2.3022e+00
   4.3450e-02]]


In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))


Saving ozone.csv to ozone.csv
User uploaded file "ozone.csv" with length 58481 bytes


Après le téléchargement, le fichier sera disponible dans l'environnement Colab. Si votre fichier s'appelle par exemple `Data.txt`, vous pourrez y accéder en utilisant `'./Data.txt'` ou simplement `'Data.txt'` dans votre code NumPy. Assurez-vous d'ajuster le nom du fichier et le chemin dans la cellule qui a causé l'erreur précédente.